### PR TITLE
Addition of an optional  REnvironment argument to REngine.Evaluate

### PR DESCRIPTION
**Pull request by guillaumejamet**
This proposed modification to REngine.cs simply add an optional REnvironment argument to methods 
REngine.Evaluate, REngine.Defer and REngine.Parse
If the environment argument is missing or null then evaluation occurs in the REngine.GlobalEnvironment.
This modfication allows to safely have independent objects accessing REngine by working in separate environment without the risk of variable name collision.
This may help solving issues like the following "multiple instances/sessions" : #46 #24

### CODE REVIEW

**Comment by jmp75** [comment]
@guillaumejamet I apologise for not looking at this earlier since your request, due to professional and personal circumstances. I am currently merging these changes.

**Comment by wiseman13** [comment]
Is there an eta on a new build going to NuGet with this functionality?

**Comment by wiseman13** [comment]
@guillaumejamet so when wanting to setup a new REnvironment() what would be the process? I see that the Global environment using the DangerousGetHandle call, but how do are we supposed to call the private static CreateInstance() if we want a new instance to populate an REnvironment with?

**Comment by guillaumejamet** [comment]
@wiseman13 Hope this short example will help: 
You can create a `RDotNet.REnvironment` this way with parent the global environment
`rEnvironment1 = REngine.CreateEnvironment(REngine.GlobalEnvironment);`
And (if needed) assign a name to it in the global env with
`REngine.GlobalEnvironment.SetSymbol("env1", rEnvironment1);`
You can  populate your env like this
`rEnvironment1.SetSymbol("a", REngine.CreateInteger(123));`
And then use the evaluate method
`int b= REngine.Evaluate("a+1", rEnvironment1).AsInteger[0]`
Then b should be 124!
Feel free to revert if not clear.

**Comment by wiseman13** [comment]
I see a CreateEvnironment call in the REngineExtension class, but not in REngine. Is this what you have to do then?

    REngine.SetEnvironmentVariables();
    var engine = REngine.GetInstance();
    engine.AutoPrint = false;
    engine.Evaluate("options(error = function() traceback(2))");

    var rEnv = REngineExtension.CreateIsolatedEnvironment(engine);
    rEnv.SetSymbol("a", engine.CreateInteger(123));
    int b = engine.Evaluate("a+1", rEnv).AsInteger()[0];

**Comment by guillaumejamet** [comment]
@wiseman13 
It should not be a problem for you that CreateEnvironment is defined in REngineExtension ?
( CreateIsolatedEnvironment is also defined in REngineExtension )
Anyway, your example should work also. The resulting hierarchy of nested environments might be different. You have to test and investigate depending on your particular needs.

**Comment by irkgreen** [comment]
Hello,

I am hoping this feature will prevent IIS from crashing when more than one user evaluates R code at the same time. As @wiseman13 says, I don't see a createEnvironment in REngine so I tried his code. Unfortunately, I get an error:

RDotNet.EvaluationException: 'Error: use of NULL environment is defunct

Is there a way to make the env not null? I am using VB.Net

        REngine.SetEnvironmentVariables()
        Dim engine = REngine.GetInstance()
        engine.AutoPrint = False
        engine.Evaluate("options(error = function() traceback(2))")
        Dim rEnv = REngineExtension.CreateIsolatedEnvironment(engine)
        rEnv.SetSymbol("a", engine.CreateInteger(123))
        Dim b As Integer = engine.Evaluate("a+1", rEnv).AsInteger()(0)

**Pull request merged**
